### PR TITLE
Updated the api to work with the latest version from crunchyroll

### PR DESCRIPTION
**Pull request by maalni**
Crunchyroll has changed their api version (again...).
These little changes should bring the server back to life.

### CODE REVIEW

**Comment by maalni** [comment]
I will close this pull request, since i made a (big/minor) mistake.
I fiddled the android app and implemented the api like the app, ran the test and got an valid session and i believed it would work again (since the old way didn't issue an session). But crunchyroll wont accept it's own issued session lol. I tested a bit around locally and found another way to get valid sessions by using the old apis, but changing the values of the request to the new one.

**Comment by onestay** [comment]
You think you could submit a PR to fix the issue?

**Comment by maalni** [comment]
Yeah i will try my best, but it will take some time, since im currently in my exam period until the 20th.

**Comment by onestay** [comment]
It should work again. I did what you described and set the new request values of `version` and `access_token` to the ones from your PR. Apparently everything works again. Thanks a lot for your effort!

**Comment by onestay** [comment]
Ah nvm, seems like it's broken again. Worked for a short period yesterday

**Comment by onestay** [comment]
Maybe the issue is that they're invalidating the access token? If you are able to get a valid one could you DM it to me? Maybe they're watching this repo and invalidating the ones we use?

**Pull request closed without merging**
